Repository w3c/specberus, pull requests merged in 2018-04, with the labels that each got.

#742 chore(package): update mocha to version 5.0.5
  package.json
Labels: greenkeeper

#740 Implementation report in metadata
  README.md
  lib/rules/metadata/profile.js
  lib/rules/sotd/implementation.js
  test/rules.js
  test/samples.json
Labels: enhancement

#743 Underline links in footer (invisible otherwise)
  public/css/specberus.css
Labels: UI, bug

#744 chore(package): update mocha to version 5.1.0
  package.json
Labels: greenkeeper

#745 chore(package): update mocha to version 5.1.1
  package.json
Labels: greenkeeper
