Repository w3c/specberus, pull requests merged in 2019-01, with the labels that each got.

#789 Miscellaneous fixes
  lib/rules.json
Labels: bug, documentation

#798 'npm run audit': make more robust (improve regex)
  known-vulns.txt
  package.json
Labels: bug, security, testing

#800 add w3c.json
  w3c.json
Labels: enhancement
